### PR TITLE
fix: remove all triggers on the api integration test pipeline

### PR DESCRIPTION
**Pull request by takla21**
GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## Description

I've made sure that the Api Integration pipeline is not triggered after a commit for any branch.

## Impact on version

- [ ] **Major**
  - The template structure was changed.
- [ ] **Minor**
  - New functionalities were added.
- [x] **Patch**
  - A bug in behavior was fixed.
  - Documentation was changed.

### Always applicable
No matter your changes, these checks always apply.
- [x] Your conventional commits are aligned with the **Impact on version** section.
- [x] Updated [CHANGELOG.md](../CHANGELOG.md).
  - Use the latest Major.Minor.X header if you do a **Patch** change.
  - Create a new Major.Minor.X header if you do a **Minor** or **Major** change.
  - If you create a new header, it aligns with the **Impact on version** section and matches what is generated in the build pipeline.
- [x] Documentation files were updated according with the changes.
  - Update `README.md` and `TemplateConfig.md` if you made changes to **templating**.
  - Update `AzurePipelines.md` and `APP_README.md` if you made changes to **pipelines**.
  - Update `Diagnostics.md` if you made changes to **diagnostic tools**.
  - Update `Architecture.md` and its diagrams if you made **architecture decisions** or if you introduced new **recipes**.
  - ...and so forth: Make sure you update the documentation files associated to the recipes you changed. Review the topics by looking at the content of the `doc/` folder.
- [x] Images about the template are referenced from the [wiki](https://github.com/nventive/UnoApplicationTemplate/wiki/Images) and added as images in this git.
- [x] TODO comments are hints for next steps for users of the template and not planned work.

### Contextual
Based on your changes these checks may not apply.
- [ ] Automated tests for the changes have been added/updated.
- [ ] Tested on all relevant platforms

### CODE REVIEW

**Review by Guidemarcus — APPROVED** [review]

**Comment by carlh98** [comment]
I think the commit should use `fix` or `chore` instead of `ci`.
is that correct @jeanplevesque?

**Comment by jeanplevesque** [comment]
> @takla21 I think the commit should use `fix` or `chore` instead of `ci`. is that correct @jeanplevesque?

Correct.

**Comment by jeanplevesque** [comment]
@takla21 
image

**Comment by takla21** [comment]
I though that `ci` would also count as a Path increment. Also, that's my reflex to cross item in the checklist as an acknowledgment  of the item, but didn't applied in this PR. I've uncrossed them though

**Review by Soap-141 — APPROVED** [review]
You could rename the PR to the actual commit :)

**Comment by takla21** [comment]
@jeanplevesque nvm I misunderstood the new PR checklist. I've made sure to check them all and add a notes in the changelog

**Review by carlh98 — APPROVED** [review]

**Pull request merged**
