### PR TITLE
Update Uno 3.0

### PR DESCRIPTION
**Pull request by MatFillion**
GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature
- Code style update (formatting)
- Refactoring (no functional changes, no api changes)
- Build or CI related changes
- Documentation content changes
- Other... Please describe:

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [ ] Tested on all relevant platforms

### CODE REVIEW

**Comment by MatFillion** [comment]
@GuillaumeSE 

- [ ] seems some navigations hang on iOS on latest dev  @carlh98 noticed the issue

**Comment by jcantin-nventive** [comment]
@MatFillion this would be very helpful! Is this PR still active?

**Comment by MatFillion** [comment]
@jcantin-nventive  @GuillaumeSE was working on it but if you have time to continue it would be good! There's probably not much left.

**Comment by vincentcastagna** [comment]
We can close this PR. 
This has been done here => https://github.com/nventive/UnoApplicationTemplate/pull/37

**Pull request closed without merging**
